In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt

In [11]:
df = pd.read_csv("C:/Users/shubh/Desktop/smart_toronto_traffic_dashboard/Data/Motor_Vehicle_Collisions_Data.csv")

In [12]:
df.head()

,_id,ACCNUM,DATE,TIME,STREET1,STREET2,OFFSET,ROAD_CLASS,DISTRICT,ACCLOC,...,SPEEDING,AG_DRIV,REDLIGHT,ALCOHOL,DISABILITY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,DIVISION
0,1,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,Yes,Yes,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55
1,2,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,Yes,Yes,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55
2,3,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,Yes,Yes,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55
3,4,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,Yes,Yes,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55
4,5,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,Yes,Yes,NaN,Yes,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18957 entries, 0 to 18956
Data columns (total 49 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   _id                18957 non-null  int64
 1   ACCNUM             14027 non-null  float64
 2   DATE               18957 non-null  object
 3   TIME               18957 non-null  int64
 4   STREET1            18957 non-null  object
 5   STREET2            17251 non-null  object
 6   OFFSET             3820 non-null   object
 7   ROAD_CLASS         18471 non-null  object
 8   DISTRICT           18728 non-null  object
 9   ACCLOC             13501 non-null  object
 10  TRAFFCTL           18882 non-null  object
 11  VISIBILITY         18933 non-null  object
 12  LIGHT              18953 non-null  object
 13  RDSFCOND           18928 non-null  object
 14  ACCLASS            18956 non-null  object
 15  IMPACTYPE          18930 non-null  object
 16  INVTYPE            18941 non-null  object
 17  INVAGE             18957 non-null  object
 18  INJURY             10060 non-null  object
 19  FATAL_NO           870 non-null    float64
 20  INITDIR            13680 non-null  object
 21  VEHTYPE            15470 non-null  object
 22  MANOEUVER          11004 non-null  object
 23  DRIVACT            9668 non-null   object
 24  DRIVCOND           9666 non-null   object
 25  PEDTYPE            3229 non-null   object
 26  PEDACT             3227 non-null   object
 27  PEDCOND            3246 non-null   object
 28  CYCLISTYPE         805 non-null    object
 29  CYCACT             802 non-null    object
 30  CYCCOND            800 non-null    object
 31  PEDESTRIAN         7688 non-null   object
 32  CYCLIST            1986 non-null   object
 33  AUTOMOBILE         17230 non-null  object
 34  MOTORCYCLE         1684 non-null   object
 35  TRUCK              1169 non-null   object
 36  TRSN_CITY_VEH      1148 non-null   object
 37  EMERG_VEH          49 non-null     object
 38  PASSENGER          7183 non-null   object
 39  SPEEDING           2694 non-null   object
 40  AG_DRIV            9836 non-null   object
 41  REDLIGHT           1577 non-null   object
 42  ALCOHOL            808 non-null    object
 43  DISABILITY         493 non-null    object
 44  HOOD_158           18957 non-null  object
 45  NEIGHBOURHOOD_158  18957 non-null  object
 46  HOOD_140           18957 non-null  object
 47  NEIGHBOURHOOD_140  18957 non-null  object
 48  DIVISION           18957 non-null  object
dtypes: float64(2), int64(2), object(45)
memory usage: 7.1+ MB

In [15]:
df.describe()

                _id        ACCNUM          TIME    FATAL_NO
count  18957.000000  1.402700e+04  18957.000000  870.000000
mean    9479.000000  5.576714e+08   1364.956428   28.752874
std     5472.558862  1.180026e+09    631.310388   17.657001
min        1.000000  2.530100e+04      0.000000    1.000000
25%     4740.000000  1.034561e+06    924.000000   14.000000
50%     9479.000000  1.220029e+06   1450.000000   27.500000
75%    14218.000000  1.386958e+06   1852.000000   42.000000
max    18957.000000  4.008024e+09   2359.000000   78.000000

In [22]:
df["DATE"] = pd.to_datetime(df["DATE"])

In [23]:
df["datetime"] = df["DATE"] + pd.to_timedelta(df["TIME"], unit='m')

In [25]:
df["hour"] = df["datetime"].dt.hour

In [26]:
df["day_of_week"] = df["datetime"].dt.dayofweek

In [27]:
df["is_weekend"] = df["day_of_week"] >= 5

In [33]:
df[["DATE", "TIME", "datetime", "hour", "day_of_week", "is_weekend"]].head()

        DATE  TIME            datetime  hour  day_of_week  is_weekend
0 2006-01-01   236 2006-01-01 03:56:00     3            6        True
1 2006-01-01   236 2006-01-01 03:56:00     3            6        True
2 2006-01-01   236 2006-01-01 03:56:00     3            6        True
3 2006-01-01   236 2006-01-01 03:56:00     3            6        True
4 2006-01-01   236 2006-01-01 03:56:00     3            6        True

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18957 entries, 0 to 18956
Data columns (total 53 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   _id                18957 non-null  int64
 1   ACCNUM             14027 non-null  float64
 2   DATE               18957 non-null  datetime64[ns]
 3   TIME               18957 non-null  int64
 4   STREET1            18957 non-null  object
 5   STREET2            17251 non-null  object
 6   OFFSET             3820 non-null   object
 7   ROAD_CLASS         18471 non-null  object
 8   DISTRICT           18728 non-null  object
 9   ACCLOC             13501 non-null  object
 10  TRAFFCTL           18882 non-null  object
 11  VISIBILITY         18933 non-null  object
 12  LIGHT              18953 non-null  object
 13  RDSFCOND           18928 non-null  object
 14  ACCLASS            18956 non-null  object
 15  IMPACTYPE          18930 non-null  object
 16  INVTYPE            18941 non-null  object
 17  INVAGE             18957 non-null  object
 18  INJURY             10060 non-null  object
 19  FATAL_NO           870 non-null    float64
 20  INITDIR            13680 non-null  object
 21  VEHTYPE            15470 non-null  object
 22  MANOEUVER          11004 non-null  object
 23  DRIVACT            9668 non-null   object
 24  DRIVCOND           9666 non-null   object
 25  PEDTYPE            3229 non-null   object
 26  PEDACT             3227 non-null   object
 27  PEDCOND            3246 non-null   object
 28  CYCLISTYPE         805 non-null    object
 29  CYCACT             802 non-null    object
 30  CYCCOND            800 non-null    object
 31  PEDESTRIAN         7688 non-null   object
 32  CYCLIST            1986 non-null   object
 33  AUTOMOBILE         17230 non-null  object
 34  MOTORCYCLE         1684 non-null   object
 35  TRUCK              1169 non-null   object
 36  TRSN_CITY_VEH      1148 non-null   object
 37  EMERG_VEH          49 non-null     object
 38  PASSENGER          7183 non-null   object
 39  SPEEDING           2694 non-null   object
 40  AG_DRIV            9836 non-null   object
 41  REDLIGHT           1577 non-null   object
 42  ALCOHOL            808 non-null    object
 43  DISABILITY         493 non-null    object
 44  HOOD_158           18957 non-null  object
 45  NEIGHBOURHOOD_158  18957 non-null  object
 46  HOOD_140           18957 non-null  object
 47  NEIGHBOURHOOD_140  18957 non-null  object
 48  DIVISION           18957 non-null  object
 49  datetime           18957 non-null  datetime64[ns]
 50  hour               18957 non-null  int32
 51  day_of_week        18957 non-null  int32
 52  is_weekend         18957 non-null  bool
dtypes: bool(1), datetime64[ns](2), float64(2), int32(2), int64(2), object(44)
memory usage: 7.4+ MB

In [35]:
df["TIME"].unique()

array([ 236,  315,  705, ..., 1839,  346,  411])

In [36]:
df

,_id,ACCNUM,DATE,TIME,STREET1,STREET2,OFFSET,ROAD_CLASS,DISTRICT,ACCLOC,...,DISABILITY,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,DIVISION,datetime,hour,day_of_week,is_weekend
0,1,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True
1,2,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True
2,3,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True
3,4,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True
4,5,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,NaN,60,Woodbine-Lumsden,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18952,18953,3.002957e+09,2023-12-26,2008,MCCOWAN RD,ELLESMERE RD,NaN,Major Arterial,NaN,Intersection Related,...,NaN,142,Woburn North,137,Woburn (137),D43,2023-12-27 09:28:00,9,2,False
18953,18954,3.002971e+09,2023-12-28,1911,DUFFERIN ST,FISHER ST,NaN,Minor Arterial,Toronto and East York,Intersection Related,...,NaN,84,Little Portugal,84,Little Portugal (84),D14,2023-12-29 07:51:00,7,4,False
18954,18955,3.002971e+09,2023-12-28,1911,DUFFERIN ST,FISHER ST,NaN,Minor Arterial,Toronto and East York,Intersection Related,...,NaN,84,Little Portugal,84,Little Portugal (84),D14,2023-12-29 07:51:00,7,4,False
18955,18956,3.002978e+09,2023-12-29,1829,DONSIDE DR,MAYBOURNE AV,NaN,Local,Scarborough,Intersection Related,...,NaN,120,Clairlea-Birchmount,120,Clairlea-Birchmount (120),D41,2023-12-30 06:29:00,6,5,True
18956,18957,3.002978e+09,2023-12-29,1829,DONSIDE DR,MAYBOURNE AV,NaN,Local,Scarborough,Intersection Related,...,NaN,120,Clairlea-Birchmount,120,Clairlea-Birchmount (120),D41,2023-12-30 06:29:00,6,5,True

In [38]:
df["datetime"].value_counts()

datetime
2012-07-20 21:40:00    19
2014-08-17 00:51:00    18
2011-08-30 23:58:00    18
2008-05-14 09:50:00    16
2021-11-08 02:54:00    15
                       ..
2022-04-12 02:47:00     1
2022-04-10 14:58:00     1
2022-05-14 12:50:00     1
2022-05-12 00:15:00     1
2022-05-08 03:10:00     1
Name: count, Length: 6850, dtype: int64

In [39]:
df["is_weekend"].value_counts()

is_weekend
False    13219
True      5738
Name: count, dtype: int64

In [46]:
print(df["VISIBILITY"].unique())
print(df["LIGHT"].unique())
print(df["RDSFCOND"].unique())

['Clear' 'Snow' 'Other' 'Rain' 'Strong wind' 'Fog, Mist, Smoke, Dust'
 'Drifting Snow' 'Freezing Rain' nan]
['Dark' 'Dark, artificial' 'Daylight' 'Dusk' 'Dawn' 'Dusk, artificial'
 'Dawn, artificial' 'Daylight, artificial' 'Other' nan]
['Wet' 'Slush' 'Dry' 'Ice' 'Loose Snow' 'Other' 'Packed Snow'
 'Spilled liquid' 'Loose Sand or Gravel' nan]

In [48]:
def map_weather(row):
    if 'Loose Snow' in str(row['RDSFCOND']) or 'Slush' in str(row['RDSFCOND']) or 'Packed Snow' in str(row['RDSFCOND']):
        return 'Snowy'
    elif 'Wet' in str(row['RDSFCOND']) or 'Spilled liquid' in str(row['RDSFCOND']):
        return 'Rainy'
    elif 'Clear' in str(row['VISIBILITY']):
        return 'Clear'
    elif 'Fog' in str(row['VISIBILITY']) or 'Mist' in str(row['VISIBILITY']):
        return 'Foggy'
    else:
        return 'Other'

df['weather_condition'] = df.apply(map_weather, axis=1)

In [51]:
df['weather_condition']

0        Rainy
1        Rainy
2        Rainy
3        Rainy
4        Rainy
         ...
18952    Rainy
18953    Rainy
18954    Rainy
18955    Rainy
18956    Rainy
Name: weather_condition, Length: 18957, dtype: object

In [69]:
print(df["VEHTYPE"].unique())

def simplify_vehicle(v):
    v = str(v)
    if 'Automobile' in v or 'Car' in v:
        return 'Car'
    elif 'Police Vehicle' in v:
        return 'Police Car'
    elif 'Truck' in v:
        return 'Truck'
    elif 'Motorcycle' in v:
        return 'Motorcycle'
    elif 'Bicycle' in v or 'Cyclist' in v:
        return 'Bicycle'
    elif 'Bus' in v:
        return 'Bus'
    else:
        return 'Other'

df['vehicle_category'] = df['VEHTYPE'].apply(simplify_vehicle)

[nan 'Automobile, Station Wagon' 'Other' 'Passenger Van'
 'Municipal Transit Bus (TTC)' 'Taxi' 'Bicycle' 'Delivery Van'
 'Motorcycle' 'Truck - Open' 'Moped' 'Pick Up Truck' 'Tow Truck'
 'Police Vehicle' 'Truck-Tractor' 'Street Car'
 'Truck - Closed (Blazer, etc)' 'Truck - Dump'
 'Bus (Other) (Go Bus, Gray Coa' 'Construction Equipment' 'Intercity Bus'
 'Truck (other)' 'Fire Vehicle' 'School Bus' 'Other Emergency Vehicle'
 'Off Road - 2 Wheels' 'Truck - Tank' 'Truck - Car Carrier' 'Ambulance'
 'Off Road - 4 Wheels' 'Off Road - Other' 'Rickshaw' 'Unknown']

In [70]:
df['vehicle_category'].tail(60)

18897         Truck
18898           Car
18899         Other
18900           Car
18901         Other
18902           Car
18903           Car
18904           Car
18905         Other
18906         Other
18907         Truck
18908           Car
18909         Other
18910         Truck
18911         Other
18912         Other
18913           Car
18914           Car
18915         Other
18916           Car
18917         Other
18918           Car
18919         Other
18920           Car
18921         Other
18922         Other
18923           Car
18924         Other
18925           Car
18926         Other
18927           Car
18928         Other
18929           Car
18930         Other
18931           Car
18932           Car
18933           Car
18934         Truck
18935       Bicycle
18936           Car
18937    Police Car
18938         Other
18939         Other
18940         Other
18941         Other
18942           Car
18943         Other
18944           Car
18945           Car
18946         Other
18947         Other
18948         Other
18949         Other
18950         Other
18951           Car
18952         Other
18953         Other
18954           Car
18955           Car
18956         Other
Name: vehicle_category, dtype: object

In [71]:
print(df["INJURY"].unique())
injury_map = {
    'Fatal': 3,
    'Major': 2,
    'Major Injury': 2,
    'Minor': 1,
    'Non-Fatal Injury': 1,
    'None': 0
}

df['injury_severity'] = df['INJURY'].map(injury_map).fillna(0)

['Major' 'Minor' nan 'Fatal' 'Minimal']

In [72]:
df.head()

,_id,ACCNUM,DATE,TIME,STREET1,STREET2,OFFSET,ROAD_CLASS,DISTRICT,ACCLOC,...,HOOD_140,NEIGHBOURHOOD_140,DIVISION,datetime,hour,day_of_week,is_weekend,weather_condition,vehicle_category,injury_severity
0,1,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,2.0
1,2,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,1.0
2,3,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Car,1.0
3,4,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,1.0
4,5,893184.0,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,1.0

In [74]:
df.drop(["VEHTYPE","INJURY", "VISIBILITY", "LIGHT", "RDSFCOND"], axis=1, inplace=True, errors='ignore')

In [75]:
df

,_id,ACCNUM,DATE,TIME,STREET1,STREET2,OFFSET,ROAD_CLASS,DISTRICT,ACCLOC,...,HOOD_140,NEIGHBOURHOOD_140,DIVISION,datetime,hour,day_of_week,is_weekend,weather_condition,vehicle_category,injury_severity
0,1,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,2.0
1,2,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,1.0
2,3,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Car,1.0
3,4,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,1.0
4,5,8.931840e+05,2006-01-01,236,WOODBINE AVE,O CONNOR DR,NaN,Major Arterial,Toronto and East York,Intersection Related,...,60,Woodbine-Lumsden (60),D55,2006-01-01 03:56:00,3,6,True,Rainy,Other,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18952,18953,3.002957e+09,2023-12-26,2008,MCCOWAN RD,ELLESMERE RD,NaN,Major Arterial,NaN,Intersection Related,...,137,Woburn (137),D43,2023-12-27 09:28:00,9,2,False,Rainy,Other,2.0
18953,18954,3.002971e+09,2023-12-28,1911,DUFFERIN ST,FISHER ST,NaN,Minor Arterial,Toronto and East York,Intersection Related,...,84,Little Portugal (84),D14,2023-12-29 07:51:00,7,4,False,Rainy,Other,3.0
18954,18955,3.002971e+09,2023-12-28,1911,DUFFERIN ST,FISHER ST,NaN,Minor Arterial,Toronto and East York,Intersection Related,...,84,Little Portugal (84),D14,2023-12-29 07:51:00,7,4,False,Rainy,Car,0.0
18955,18956,3.002978e+09,2023-12-29,1829,DONSIDE DR,MAYBOURNE AV,NaN,Local,Scarborough,Intersection Related,...,120,Clairlea-Birchmount (120),D41,2023-12-30 06:29:00,6,5,True,Rainy,Car,0.0
18956,18957,3.002978e+09,2023-12-29,1829,DONSIDE DR,MAYBOURNE AV,NaN,Local,Scarborough,Intersection Related,...,120,Clairlea-Birchmount (120),D41,2023-12-30 06:29:00,6,5,True,Rainy,Other,2.0

In [80]:
df1 = pd.read_csv("C:/Users/shubh/Desktop/smart_toronto_traffic_dashboard/Data/toronto_weather_report.csv", skiprows=2)

In [81]:
df1

,time,temperature_2m (°C),weather_code (wmo code),wind_speed_10m (km/h),visibility (m),wind_direction_10m (°),precipitation (mm)
0,2025-10-23T00:00,6.1,2,10.5,15400.0,221,0.0
1,2025-10-23T01:00,6.2,1,10.2,13800.0,225,0.0
2,2025-10-23T02:00,6.5,0,15.9,15300.0,245,0.0
3,2025-10-23T03:00,6.3,0,10.5,15200.0,254,0.0
4,2025-10-23T04:00,6.5,0,15.2,17100.0,256,0.0
...,...,...,...,...,...,...,...
163,2025-10-29T19:00,5.8,51,17.7,18840.0,52,0.3
164,2025-10-29T20:00,5.7,51,19.4,22760.0,48,0.3
165,2025-10-29T21:00,5.9,51,18.6,23220.0,46,0.1
166,2025-10-29T22:00,6.2,51,16.8,23680.0,45,0.1
167,2025-10-29T23:00,6.4,51,15.5,24140.0,44,0.1

In [82]:
df1.head()

,time,temperature_2m (°C),weather_code (wmo code),wind_speed_10m (km/h),visibility (m),wind_direction_10m (°),precipitation (mm)
0,2025-10-23T00:00,6.1,2,10.5,15400.0,221,0.0
1,2025-10-23T01:00,6.2,1,10.2,13800.0,225,0.0
2,2025-10-23T02:00,6.5,0,15.9,15300.0,245,0.0
3,2025-10-23T03:00,6.3,0,10.5,15200.0,254,0.0
4,2025-10-23T04:00,6.5,0,15.2,17100.0,256,0.0

In [83]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   time                     168 non-null    object
 1   temperature_2m (°C)      168 non-null    float64
 2   weather_code (wmo code)  168 non-null    int64
 3   wind_speed_10m (km/h)    168 non-null    float64
 4   visibility (m)           168 non-null    float64
 5   wind_direction_10m (°)   168 non-null    int64
 6   precipitation (mm)       168 non-null    float64
dtypes: float64(4), int64(2), object(1)
memory usage: 9.3+ KB

In [84]:
new_column_names = {
    'time':'datetime','temperature_2m (°C)':'temperature','weather_code (wmo code)':'weather_code',
    'wind_speed_10m (km/h)':'wind_speed','visibility (m)':'visibility','wind_direction_10m (°)':'wind_direction','precipitation (mm)':'precipitation' 'new_col_X',
}

df1.rename(columns=new_column_names, inplace=True)

In [85]:
df1

,datetime,temperature,weather_code,wind_speed,visibility,wind_direction,precipitationnew_col_X
0,2025-10-23T00:00,6.1,2,10.5,15400.0,221,0.0
1,2025-10-23T01:00,6.2,1,10.2,13800.0,225,0.0
2,2025-10-23T02:00,6.5,0,15.9,15300.0,245,0.0
3,2025-10-23T03:00,6.3,0,10.5,15200.0,254,0.0
4,2025-10-23T04:00,6.5,0,15.2,17100.0,256,0.0
...,...,...,...,...,...,...,...
163,2025-10-29T19:00,5.8,51,17.7,18840.0,52,0.3
164,2025-10-29T20:00,5.7,51,19.4,22760.0,48,0.3
165,2025-10-29T21:00,5.9,51,18.6,23220.0,46,0.1
166,2025-10-29T22:00,6.2,51,16.8,23680.0,45,0.1
167,2025-10-29T23:00,6.4,51,15.5,24140.0,44,0.1

In [86]:
df1['datetime'] = pd.to_datetime(df['datetime'])

In [88]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   datetime                168 non-null    datetime64[ns]
 1   temperature             168 non-null    float64
 2   weather_code            168 non-null    int64
 3   wind_speed              168 non-null    float64
 4   visibility              168 non-null    float64
 5   wind_direction          168 non-null    int64
 6   precipitationnew_col_X  168 non-null    float64
dtypes: datetime64[ns](1), float64(4), int64(2)
memory usage: 9.3 KB

In [89]:
df = df.sort_values('datetime')
df1 = df1.sort_values('datetime')

In [92]:
merged_df = pd.merge_asof(
    left=df,
    right=df1,
    on='datetime',
    direction='nearest'
)

In [98]:
merged_df.to_csv("C:/Users/shubh/Desktop/smart_toronto_traffic_dashboard/Data/traffic_weather_merged.csv", index=False)
print("✅ Merging complete! Saved as traffic_weather_merged.csv")

✅ Merging complete! Saved as traffic_weather_merged.csv

In [99]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18957 entries, 0 to 18956
Data columns (total 57 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     18957 non-null  int64
 1   ACCNUM                  14027 non-null  float64
 2   DATE                    18957 non-null  datetime64[ns]
 3   TIME                    18957 non-null  int64
 4   STREET1                 18957 non-null  object
 5   STREET2                 17251 non-null  object
 6   OFFSET                  3820 non-null   object
 7   ROAD_CLASS              18471 non-null  object
 8   DISTRICT                18728 non-null  object
 9   ACCLOC                  13501 non-null  object
 10  TRAFFCTL                18882 non-null  object
 11  ACCLASS                 18956 non-null  object
 12  IMPACTYPE               18930 non-null  object
 13  INVTYPE                 18941 non-null  object
 14  INVAGE                  18957 non-null  object
 15  FATAL_NO                870 non-null    float64
 16  INITDIR                 13680 non-null  object
 17  MANOEUVER               11004 non-null  object
 18  DRIVACT                 9668 non-null   object
 19  DRIVCOND                9666 non-null   object
 20  PEDTYPE                 3229 non-null   object
 21  PEDACT                  3227 non-null   object
 22  PEDCOND                 3246 non-null   object
 23  CYCLISTYPE              805 non-null    object
 24  CYCACT                  802 non-null    object
 25  CYCCOND                 800 non-null    object
 26  PEDESTRIAN              7688 non-null   object
 27  CYCLIST                 1986 non-null   object
 28  AUTOMOBILE              17230 non-null  object
 29  MOTORCYCLE              1684 non-null   object
 30  TRUCK                   1169 non-null   object
 31  TRSN_CITY_VEH           1148 non-null   object
 32  EMERG_VEH               49 non-null     object
 33  PASSENGER               7183 non-null   object
 34  SPEEDING                2694 non-null   object
 35  AG_DRIV                 9836 non-null   object
 36  REDLIGHT                1577 non-null   object
 37  ALCOHOL                 808 non-null    object
 38  DISABILITY              493 non-null    object
 39  HOOD_158                18957 non-null  object
 40  NEIGHBOURHOOD_158       18957 non-null  object
 41  HOOD_140                18957 non-null  object
 42  NEIGHBOURHOOD_140       18957 non-null  object
 43  DIVISION                18957 non-null  object
 44  datetime                18957 non-null  datetime64[ns]
 45  hour                    18957 non-null  int32
 46  day_of_week             18957 non-null  int32
 47  is_weekend              18957 non-null  bool
 48  weather_condition       18957 non-null  object
 49  vehicle_category        18957 non-null  object
 50  injury_severity         18957 non-null  float64
 51  temperature             18957 non-null  float64
 52  weather_code            18957 non-null  int64
 53  wind_speed              18957 non-null  float64
 54  visibility              18957 non-null  float64
 55  wind_direction          18957 non-null  int64
 56  precipitationnew_col_X  18957 non-null  float64
dtypes: bool(1), datetime64[ns](2), float64(7), int32(2), int64(4), object(41)
memory usage: 8.0+ MB

In [100]:
merged_df['hour'] = merged_df['datetime'].dt.hour
merged_df['day_of_week'] = merged_df['datetime'].dt.day_name()
merged_df['is_weekend'] = merged_df['day_of_week'].isin(['Saturday', 'Sunday'])

In [101]:
merged_df.to_csv("C:/Users/shubh/Desktop/smart_toronto_traffic_dashboard/Data/combined.csv", index=False)

In [102]:
df_2 = pd.read_csv("C:/Users/shubh/Desktop/smart_toronto_traffic_dashboard/Data/combined.csv")

In [103]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18957 entries, 0 to 18956
Data columns (total 57 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   _id                     18957 non-null  int64
 1   ACCNUM                  14027 non-null  float64
 2   DATE                    18957 non-null  object
 3   TIME                    18957 non-null  int64
 4   STREET1                 18957 non-null  object
 5   STREET2                 17251 non-null  object
 6   OFFSET                  3820 non-null   object
 7   ROAD_CLASS              18471 non-null  object
 8   DISTRICT                18728 non-null  object
 9   ACCLOC                  13501 non-null  object
 10  TRAFFCTL                18882 non-null  object
 11  ACCLASS                 18956 non-null  object
 12  IMPACTYPE               18930 non-null  object
 13  INVTYPE                 18941 non-null  object
 14  INVAGE                  18957 non-null  object
 15  FATAL_NO                870 non-null    float64
 16  INITDIR                 13680 non-null  object
 17  MANOEUVER               11004 non-null  object
 18  DRIVACT                 9668 non-null   object
 19  DRIVCOND                9666 non-null   object
 20  PEDTYPE                 3229 non-null   object
 21  PEDACT                  3227 non-null   object
 22  PEDCOND                 3246 non-null   object
 23  CYCLISTYPE              805 non-null    object
 24  CYCACT                  802 non-null    object
 25  CYCCOND                 800 non-null    object
 26  PEDESTRIAN              7688 non-null   object
 27  CYCLIST                 1986 non-null   object
 28  AUTOMOBILE              17230 non-null  object
 29  MOTORCYCLE              1684 non-null   object
 30  TRUCK                   1169 non-null   object
 31  TRSN_CITY_VEH           1148 non-null   object
 32  EMERG_VEH               49 non-null     object
 33  PASSENGER               7183 non-null   object
 34  SPEEDING                2694 non-null   object
 35  AG_DRIV                 9836 non-null   object
 36  REDLIGHT                1577 non-null   object
 37  ALCOHOL                 808 non-null    object
 38  DISABILITY              493 non-null    object
 39  HOOD_158                18957 non-null  object
 40  NEIGHBOURHOOD_158       18957 non-null  object
 41  HOOD_140                18957 non-null  object
 42  NEIGHBOURHOOD_140       18957 non-null  object
 43  DIVISION                18957 non-null  object
 44  datetime                18957 non-null  object
 45  hour                    18957 non-null  int64
 46  day_of_week             18957 non-null  object
 47  is_weekend              18957 non-null  bool
 48  weather_condition       18957 non-null  object
 49  vehicle_category        18957 non-null  object
 50  injury_severity         18957 non-null  float64
 51  temperature             18957 non-null  float64
 52  weather_code            18957 non-null  int64
 53  wind_speed              18957 non-null  float64
 54  visibility              18957 non-null  float64
 55  wind_direction          18957 non-null  int64
 56  precipitationnew_col_X  18957 non-null  float64
dtypes: bool(1), float64(7), int64(5), object(44)
memory usage: 8.1+ MB

### 🧹 Data Cleaning & Processing Notes

**Goal:** Prepare clean and usable data for analysis by merging Toronto traffic and weather datasets.

---

#### 1. Data Import

* Imported both datasets:

  * `toronto_traffic_data.csv`
  * `toronto_weather_report.csv`
* Inspected columns, data types, and null values using `.info()` and `.head()`.

---

#### 2. Handling Missing Data

* Dropped unnecessary or empty rows using `dropna()` where appropriate.
* Filled minor missing values with `fillna(method='ffill')` to maintain continuity in time series.

---

#### 3. Datetime Conversion

* Converted both datasets’ datetime columns using:

  ```python
  pd.to_datetime(df['datetime'])
  ```
* Ensured both datasets were **sorted by datetime** to allow accurate time-based merging.

---

#### 4. Feature Engineering

* Created new useful time-based features:

  ```python
  merged_df['hour'] = merged_df['datetime'].dt.hour
  merged_df['day_of_week'] = merged_df['datetime'].dt.day_name()
  merged_df['is_weekend'] = merged_df['day_of_week'].isin(['Saturday', 'Sunday'])
  ```
* Added `weather_condition` column based on weather status (e.g., sunny, cloudy, rain).

---

#### 5. Data Merging

* Merged traffic and weather datasets using `pd.merge_asof()` for **nearest timestamp matching**:

  ```python
  merged_df = pd.merge_asof(
      traffic_df.sort_values('datetime'),
      weather_df.sort_values('datetime'),
      on='datetime',
      direction='nearest'
  )
  ```
* This ensures each traffic record matches with the closest weather observation in time.

---

#### 6. Final Output

* Saved the cleaned and merged dataset to:

  ```
  C:/Users/shubh/Desktop/smart_toronto_traffic_dashboard/Data/combined.csv
  ```
* Verified output shape and columns using `.info()` and `.head()`.

---

✅ **Result:**
A clean, merged dataset combining traffic and weather data, ready for analysis and visualization.